### ISSUE TITLE
It does unnecessary download inside Kubernetes

### ISSUE THREAD

**Issue by barislegion** [curl/curl-container#67]
When I run container on my local I get only the response from my end point. But inside Kubernetes I see unnecessary download output as if I added -o to my commands but I didn't. So I can't get clear JSON output from my REST endpoint. 

Kubernetes: 1.23.x
image: curlimages/curl:8.10.1

I use it with Kubernetes cronjobs.

```
apiVersion: batch/v1
kind: CronJob
metadata:
  name: hello
spec:
  schedule: "* * * * *"
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: curl-job
            image: curlimages/curl:8.10.1
            imagePullPolicy: IfNotPresent
            args:
            - -X
            - POST
            - https://my-api-end-point
          restartPolicy: OnFailure
```
